# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/apihub/display_settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<google/cloud/apigeeregistry/v1/apihub/display_settings.proto\x12%google.cloud.apigeeregistry.v1.apihub\"\x8c\x01\n\x0f\x44isplaySettings\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0corganization\x18\x04 \x01(\t\x12\x19\n\x11\x61pi_guide_enabled\x18\x05 \x01(\x08\x12\x19\n\x11\x61pi_score_enabled\x18\x06 \x01(\x08\x42g\n)com.google.cloud.apigeeregistry.v1.apihubB\x14\x44isplaySettingsProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_DISPLAYSETTINGS = DESCRIPTOR.message_types_by_name['DisplaySettings']
DisplaySettings = _reflection.GeneratedProtocolMessageType('DisplaySettings', (_message.Message,), {
  'DESCRIPTOR' : _DISPLAYSETTINGS,
  '__module__' : 'google.cloud.apigeeregistry.v1.apihub.display_settings_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.DisplaySettings)
  })
_sym_db.RegisterMessage(DisplaySettings)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.google.cloud.apigeeregistry.v1.apihubB\024DisplaySettingsProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _DISPLAYSETTINGS._serialized_start=104
  _DISPLAYSETTINGS._serialized_end=244
# @@protoc_insertion_point(module_scope)
