# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/apihub/lifecycle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5google/cloud/apigeeregistry/v1/apihub/lifecycle.proto\x12%google.cloud.apigeeregistry.v1.apihub\"\xfc\x01\n\tLifecycle\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x46\n\x06stages\x18\x05 \x03(\x0b\x32\x36.google.cloud.apigeeregistry.v1.apihub.Lifecycle.Stage\x1a\x62\n\x05Stage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x15\n\rdisplay_order\x18\x05 \x01(\x05\x42m\n)com.google.cloud.apigeeregistry.v1.apihubB\x1a\x41piHubLifecycleModelsProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_LIFECYCLE = DESCRIPTOR.message_types_by_name['Lifecycle']
_LIFECYCLE_STAGE = _LIFECYCLE.nested_types_by_name['Stage']
Lifecycle = _reflection.GeneratedProtocolMessageType('Lifecycle', (_message.Message,), {

  'Stage' : _reflection.GeneratedProtocolMessageType('Stage', (_message.Message,), {
    'DESCRIPTOR' : _LIFECYCLE_STAGE,
    '__module__' : 'google.cloud.apigeeregistry.v1.apihub.lifecycle_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.Lifecycle.Stage)
    })
  ,
  'DESCRIPTOR' : _LIFECYCLE,
  '__module__' : 'google.cloud.apigeeregistry.v1.apihub.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.Lifecycle)
  })
_sym_db.RegisterMessage(Lifecycle)
_sym_db.RegisterMessage(Lifecycle.Stage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.google.cloud.apigeeregistry.v1.apihubB\032ApiHubLifecycleModelsProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _LIFECYCLE._serialized_start=97
  _LIFECYCLE._serialized_end=349
  _LIFECYCLE_STAGE._serialized_start=251
  _LIFECYCLE_STAGE._serialized_end=349
# @@protoc_insertion_point(module_scope)
