# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/apihub/references.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6google/cloud/apigeeregistry/v1/apihub/references.proto\x12%google.cloud.apigeeregistry.v1.apihub\x1a\x1fgoogle/api/field_behavior.proto\"\xa1\x02\n\rReferenceList\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12R\n\nreferences\x18\x06 \x03(\x0b\x32>.google.cloud.apigeeregistry.v1.apihub.ReferenceList.Reference\x1aw\n\tReference\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x19\n\x0c\x64isplay_name\x18\x02 \x01(\tB\x03\xe0\x41\x01\x12\x15\n\x08\x63\x61tegory\x18\x03 \x01(\tB\x03\xe0\x41\x01\x12\x15\n\x08resource\x18\x04 \x01(\tB\x03\xe0\x41\x01\x12\x10\n\x03uri\x18\x05 \x01(\tB\x03\xe0\x41\x01\x42\x62\n)com.google.cloud.apigeeregistry.v1.apihubB\x0fReferencesProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_REFERENCELIST = DESCRIPTOR.message_types_by_name['ReferenceList']
_REFERENCELIST_REFERENCE = _REFERENCELIST.nested_types_by_name['Reference']
ReferenceList = _reflection.GeneratedProtocolMessageType('ReferenceList', (_message.Message,), {

  'Reference' : _reflection.GeneratedProtocolMessageType('Reference', (_message.Message,), {
    'DESCRIPTOR' : _REFERENCELIST_REFERENCE,
    '__module__' : 'google.cloud.apigeeregistry.v1.apihub.references_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.ReferenceList.Reference)
    })
  ,
  'DESCRIPTOR' : _REFERENCELIST,
  '__module__' : 'google.cloud.apigeeregistry.v1.apihub.references_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.ReferenceList)
  })
_sym_db.RegisterMessage(ReferenceList)
_sym_db.RegisterMessage(ReferenceList.Reference)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.google.cloud.apigeeregistry.v1.apihubB\017ReferencesProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _REFERENCELIST_REFERENCE.fields_by_name['id']._options = None
  _REFERENCELIST_REFERENCE.fields_by_name['id']._serialized_options = b'\340A\002'
  _REFERENCELIST_REFERENCE.fields_by_name['display_name']._options = None
  _REFERENCELIST_REFERENCE.fields_by_name['display_name']._serialized_options = b'\340A\001'
  _REFERENCELIST_REFERENCE.fields_by_name['category']._options = None
  _REFERENCELIST_REFERENCE.fields_by_name['category']._serialized_options = b'\340A\001'
  _REFERENCELIST_REFERENCE.fields_by_name['resource']._options = None
  _REFERENCELIST_REFERENCE.fields_by_name['resource']._serialized_options = b'\340A\001'
  _REFERENCELIST_REFERENCE.fields_by_name['uri']._options = None
  _REFERENCELIST_REFERENCE.fields_by_name['uri']._serialized_options = b'\340A\001'
  _REFERENCELIST._serialized_start=131
  _REFERENCELIST._serialized_end=420
  _REFERENCELIST_REFERENCE._serialized_start=301
  _REFERENCELIST_REFERENCE._serialized_end=420
# @@protoc_insertion_point(module_scope)
