# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/apihub/taxonomies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6google/cloud/apigeeregistry/v1/apihub/taxonomies.proto\x12%google.cloud.apigeeregistry.v1.apihub\"\xfc\x03\n\x0cTaxonomyList\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12P\n\ntaxonomies\x18\x05 \x03(\x0b\x32<.google.cloud.apigeeregistry.v1.apihub.TaxonomyList.Taxonomy\x1a\xd4\x02\n\x08Taxonomy\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\radmin_applied\x18\x04 \x01(\x08\x12\x18\n\x10single_selection\x18\x05 \x01(\x08\x12\x17\n\x0fsearch_excluded\x18\x06 \x01(\x08\x12\x16\n\x0esystem_managed\x18\x07 \x01(\x08\x12\x15\n\rdisplay_order\x18\x08 \x01(\x05\x12V\n\x08\x65lements\x18\t \x03(\x0b\x32\x44.google.cloud.apigeeregistry.v1.apihub.TaxonomyList.Taxonomy.Element\x1a@\n\x07\x45lement\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tBl\n)com.google.cloud.apigeeregistry.v1.apihubB\x19\x41piHubTaxonomyModelsProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_TAXONOMYLIST = DESCRIPTOR.message_types_by_name['TaxonomyList']
_TAXONOMYLIST_TAXONOMY = _TAXONOMYLIST.nested_types_by_name['Taxonomy']
_TAXONOMYLIST_TAXONOMY_ELEMENT = _TAXONOMYLIST_TAXONOMY.nested_types_by_name['Element']
TaxonomyList = _reflection.GeneratedProtocolMessageType('TaxonomyList', (_message.Message,), {

  'Taxonomy' : _reflection.GeneratedProtocolMessageType('Taxonomy', (_message.Message,), {

    'Element' : _reflection.GeneratedProtocolMessageType('Element', (_message.Message,), {
      'DESCRIPTOR' : _TAXONOMYLIST_TAXONOMY_ELEMENT,
      '__module__' : 'google.cloud.apigeeregistry.v1.apihub.taxonomies_pb2'
      # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.TaxonomyList.Taxonomy.Element)
      })
    ,
    'DESCRIPTOR' : _TAXONOMYLIST_TAXONOMY,
    '__module__' : 'google.cloud.apigeeregistry.v1.apihub.taxonomies_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.TaxonomyList.Taxonomy)
    })
  ,
  'DESCRIPTOR' : _TAXONOMYLIST,
  '__module__' : 'google.cloud.apigeeregistry.v1.apihub.taxonomies_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.apihub.TaxonomyList)
  })
_sym_db.RegisterMessage(TaxonomyList)
_sym_db.RegisterMessage(TaxonomyList.Taxonomy)
_sym_db.RegisterMessage(TaxonomyList.Taxonomy.Element)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.google.cloud.apigeeregistry.v1.apihubB\031ApiHubTaxonomyModelsProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _TAXONOMYLIST._serialized_start=98
  _TAXONOMYLIST._serialized_end=606
  _TAXONOMYLIST_TAXONOMY._serialized_start=266
  _TAXONOMYLIST_TAXONOMY._serialized_end=606
  _TAXONOMYLIST_TAXONOMY_ELEMENT._serialized_start=542
  _TAXONOMYLIST_TAXONOMY_ELEMENT._serialized_end=606
# @@protoc_insertion_point(module_scope)
