apiVersion: apigeeregistry/v1
kind: TaxonomyList
metadata:
  name: apihub-taxonomies
data:
  displayName: TaxonomyList
  description: A list of taxonomies that can be used to classify resources in the registry
  taxonomies:
    - id: apihub-target-users
      displayName: Target users
      description: The intended users (consumers) of an API
      adminApplied: false
      singleSelection: false
      searchExcluded: false
      systemManaged: true
      displayOrder: 0
      elements:
        - id: team
          displayName: Team
          description: Intended for exclusive use by the producing team
        - id: internal
          displayName: Internal
          description: Available to internal teams
        - id: partner
          displayName: Partner
          description: Available to select partners
        - id: public
          displayName: Public
          description: Published for discovery by the general public
    - id: apihub-style
      displayName: Style (primary)
      description: The primary architectural style of the API
      adminApplied: false
      singleSelection: true
      searchExcluded: false
      systemManaged: true
      displayOrder: 1
      elements:
        - id: apihub-openapi
          displayName: OpenAPI
          description: https://spec.openapis.org/oas/latest.html
        - id: apihub-grpc
          displayName: gRPC
          description: https://grpc.io
        - id: apihub-graphql
          displayName: GraphQL
          description: https://graphql.org
        - id: apihub-asyncapi
          displayName: AsyncAPI
          description: https://www.asyncapi.com
        - id: apihub-soap
          displayName: SOAP
          description: https://en.wikipedia.org/wiki/Web_Services_Description_Language
    - id: apihub-team
      displayName: Team
      description: The producing team responsible for an API
      adminApplied: false
      singleSelection: true
      searchExcluded: false
      systemManaged: true
      displayOrder: 2
      elements:
        - id: example
          displayName: Example Team Name
          description: Example description
    - id: apihub-business-unit
      displayName: Business unit
      description: A business unit responsible for an API
      adminApplied: false
      singleSelection: true
      searchExcluded: false
      systemManaged: true
      displayOrder: 3
      elements:
        - id: example
          displayName: Example Business Unit Name
          description: Example description
    - id: apihub-gateway
      displayName: Gateway
      description: The type of API gateway used for a deployment
      adminApplied: false
      singleSelection: true
      searchExcluded: true
      systemManaged: true
      displayOrder: 4
      elements:
        - id: apihub-google-cloud-apigee
          displayName: Google Cloud - Apigee
          description: ""
        - id: apihub-google-cloud-api-gateway
          displayName: Google Cloud - API Gateway
          description: ""
        - id: apihub-unmanaged
          displayName: Unmanaged
          description: ""
