apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: googleapis.com-youtube
data:
  displayName: googleapis.com-youtube
  description: YouTube Data API v3
  versions:
    - metadata:
        name: v3
      data:
        specs:
          - metadata:
              name: openapi.yaml
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3
              sourceURI: https://raw.githubusercontent.com/APIs-guru/openapi-directory/754babf60fe7fae589c43afea8ff31c44cfb48e9/APIs/googleapis.com/youtube/v3/openapi.yaml
