# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/consistency_report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.cloud.apigeeregistry.v1 import word_group_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_word__group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7google/cloud/apigeeregistry/v1/consistency_report.proto\x12\x1egoogle.cloud.apigeeregistry.v1\x1a/google/cloud/apigeeregistry/v1/word_group.proto\"\xc9\x02\n\x11\x43onsistencyReport\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12W\n\x12\x63urrent_variations\x18\x03 \x03(\x0b\x32;.google.cloud.apigeeregistry.v1.ConsistencyReport.Variation\x12T\n\x0fpast_variations\x18\x04 \x03(\x0b\x32;.google.cloud.apigeeregistry.v1.ConsistencyReport.Variation\x12\x14\n\x0cunique_terms\x18\x05 \x03(\t\x1aU\n\tVariation\x12\x0c\n\x04term\x18\x01 \x01(\t\x12:\n\x07\x63luster\x18\x02 \x01(\x0b\x32).google.cloud.apigeeregistry.v1.WordGroupb\x06proto3')



_CONSISTENCYREPORT = DESCRIPTOR.message_types_by_name['ConsistencyReport']
_CONSISTENCYREPORT_VARIATION = _CONSISTENCYREPORT.nested_types_by_name['Variation']
ConsistencyReport = _reflection.GeneratedProtocolMessageType('ConsistencyReport', (_message.Message,), {

  'Variation' : _reflection.GeneratedProtocolMessageType('Variation', (_message.Message,), {
    'DESCRIPTOR' : _CONSISTENCYREPORT_VARIATION,
    '__module__' : 'google.cloud.apigeeregistry.v1.consistency_report_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.ConsistencyReport.Variation)
    })
  ,
  'DESCRIPTOR' : _CONSISTENCYREPORT,
  '__module__' : 'google.cloud.apigeeregistry.v1.consistency_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.ConsistencyReport)
  })
_sym_db.RegisterMessage(ConsistencyReport)
_sym_db.RegisterMessage(ConsistencyReport.Variation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSISTENCYREPORT._serialized_start=141
  _CONSISTENCYREPORT._serialized_end=470
  _CONSISTENCYREPORT_VARIATION._serialized_start=385
  _CONSISTENCYREPORT_VARIATION._serialized_end=470
# @@protoc_insertion_point(module_scope)
