# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.apigeeregistry.v1 import provisioning_service_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2


class ProvisioningStub(object):
    """The service that is used for managing the data plane provisioning of the
    Registry.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateInstance = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Provisioning/CreateInstance',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteInstance = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Provisioning/DeleteInstance',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.DeleteInstanceRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.GetInstance = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Provisioning/GetInstance',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.GetInstanceRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.Instance.FromString,
                )


class ProvisioningServicer(object):
    """The service that is used for managing the data plane provisioning of the
    Registry.
    """

    def CreateInstance(self, request, context):
        """Provisions instance resources for the Registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInstance(self, request, context):
        """Deletes the Registry instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstance(self, request, context):
        """Gets details of a single Instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProvisioningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.CreateInstanceRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInstance,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.DeleteInstanceRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstance,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.GetInstanceRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.Instance.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.apigeeregistry.v1.Provisioning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Provisioning(object):
    """The service that is used for managing the data plane provisioning of the
    Registry.
    """

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Provisioning/CreateInstance',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.CreateInstanceRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Provisioning/DeleteInstance',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.DeleteInstanceRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Provisioning/GetInstance',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.GetInstanceRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_provisioning__service__pb2.Instance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
