# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from google.cloud.apigeeregistry.v1 import registry_models_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2
from google.cloud.apigeeregistry.v1 import registry_service_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class RegistryStub(object):
    """The Registry service allows teams to manage descriptions of APIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListApis = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListApis',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApisRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApisResponse.FromString,
                )
        self.GetApi = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetApi',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.FromString,
                )
        self.CreateApi = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/CreateApi',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.FromString,
                )
        self.UpdateApi = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/UpdateApi',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.FromString,
                )
        self.DeleteApi = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteApi',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListApiVersions = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListApiVersions',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiVersionsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiVersionsResponse.FromString,
                )
        self.GetApiVersion = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetApiVersion',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiVersionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.FromString,
                )
        self.CreateApiVersion = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/CreateApiVersion',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiVersionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.FromString,
                )
        self.UpdateApiVersion = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/UpdateApiVersion',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiVersionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.FromString,
                )
        self.DeleteApiVersion = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteApiVersion',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiVersionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListApiSpecs = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListApiSpecs',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecsResponse.FromString,
                )
        self.GetApiSpec = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetApiSpec',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiSpecRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
                )
        self.GetApiSpecContents = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetApiSpecContents',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiSpecContentsRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
                )
        self.CreateApiSpec = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/CreateApiSpec',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiSpecRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
                )
        self.UpdateApiSpec = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/UpdateApiSpec',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiSpecRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
                )
        self.DeleteApiSpec = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteApiSpec',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiSpecRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.TagApiSpecRevision = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/TagApiSpecRevision',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.TagApiSpecRevisionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
                )
        self.ListApiSpecRevisions = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListApiSpecRevisions',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecRevisionsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecRevisionsResponse.FromString,
                )
        self.RollbackApiSpec = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/RollbackApiSpec',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.RollbackApiSpecRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
                )
        self.DeleteApiSpecRevision = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteApiSpecRevision',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiSpecRevisionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
                )
        self.ListApiDeployments = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListApiDeployments',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentsResponse.FromString,
                )
        self.GetApiDeployment = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetApiDeployment',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiDeploymentRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
                )
        self.CreateApiDeployment = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/CreateApiDeployment',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiDeploymentRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
                )
        self.UpdateApiDeployment = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/UpdateApiDeployment',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiDeploymentRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
                )
        self.DeleteApiDeployment = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteApiDeployment',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiDeploymentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.TagApiDeploymentRevision = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/TagApiDeploymentRevision',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.TagApiDeploymentRevisionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
                )
        self.ListApiDeploymentRevisions = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListApiDeploymentRevisions',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentRevisionsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentRevisionsResponse.FromString,
                )
        self.RollbackApiDeployment = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/RollbackApiDeployment',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.RollbackApiDeploymentRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
                )
        self.DeleteApiDeploymentRevision = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteApiDeploymentRevision',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiDeploymentRevisionRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
                )
        self.ListArtifacts = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ListArtifacts',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListArtifactsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListArtifactsResponse.FromString,
                )
        self.GetArtifact = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetArtifact',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetArtifactRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.FromString,
                )
        self.GetArtifactContents = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/GetArtifactContents',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetArtifactContentsRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
                )
        self.CreateArtifact = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/CreateArtifact',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateArtifactRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.FromString,
                )
        self.ReplaceArtifact = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/ReplaceArtifact',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ReplaceArtifactRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.FromString,
                )
        self.DeleteArtifact = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Registry/DeleteArtifact',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteArtifactRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class RegistryServicer(object):
    """The Registry service allows teams to manage descriptions of APIs.
    """

    def ListApis(self, request, context):
        """ListApis returns matching APIs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApi(self, request, context):
        """GetApi returns a specified API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApi(self, request, context):
        """CreateApi creates a specified API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApi(self, request, context):
        """UpdateApi can be used to modify a specified API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApi(self, request, context):
        """DeleteApi removes a specified API and all of the resources that it
        owns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiVersions(self, request, context):
        """ListApiVersions returns matching versions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiVersion(self, request, context):
        """GetApiVersion returns a specified version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiVersion(self, request, context):
        """CreateApiVersion creates a specified version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApiVersion(self, request, context):
        """UpdateApiVersion can be used to modify a specified version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApiVersion(self, request, context):
        """DeleteApiVersion removes a specified version and all of the resources that
        it owns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiSpecs(self, request, context):
        """ListApiSpecs returns matching specs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiSpec(self, request, context):
        """GetApiSpec returns a specified spec.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiSpecContents(self, request, context):
        """GetApiSpecContents returns the contents of a specified spec.
        If specs are stored with GZip compression, the default behavior
        is to return the spec uncompressed (the mime_type response field
        indicates the exact format returned).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiSpec(self, request, context):
        """CreateApiSpec creates a specified spec.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApiSpec(self, request, context):
        """UpdateApiSpec can be used to modify a specified spec.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApiSpec(self, request, context):
        """DeleteApiSpec removes a specified spec, all revisions, and all child
        resources (e.g. artifacts).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TagApiSpecRevision(self, request, context):
        """TagApiSpecRevision adds a tag to a specified revision of a spec.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiSpecRevisions(self, request, context):
        """ListApiSpecRevisions lists all revisions of a spec.
        Revisions are returned in descending order of revision creation time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackApiSpec(self, request, context):
        """RollbackApiSpec sets the current revision to a specified prior revision.
        Note that this creates a new revision with a new revision ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApiSpecRevision(self, request, context):
        """DeleteApiSpecRevision deletes a revision of a spec.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiDeployments(self, request, context):
        """ListApiDeployments returns matching deployments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiDeployment(self, request, context):
        """GetApiDeployment returns a specified deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiDeployment(self, request, context):
        """CreateApiDeployment creates a specified deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApiDeployment(self, request, context):
        """UpdateApiDeployment can be used to modify a specified deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApiDeployment(self, request, context):
        """DeleteApiDeployment removes a specified deployment, all revisions, and all
        child resources (e.g. artifacts).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TagApiDeploymentRevision(self, request, context):
        """TagApiDeploymentRevision adds a tag to a specified revision of a
        deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiDeploymentRevisions(self, request, context):
        """ListApiDeploymentRevisions lists all revisions of a deployment.
        Revisions are returned in descending order of revision creation time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackApiDeployment(self, request, context):
        """RollbackApiDeployment sets the current revision to a specified prior
        revision. Note that this creates a new revision with a new revision ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApiDeploymentRevision(self, request, context):
        """DeleteApiDeploymentRevision deletes a revision of a deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtifacts(self, request, context):
        """ListArtifacts returns matching artifacts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """GetArtifact returns a specified artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifactContents(self, request, context):
        """GetArtifactContents returns the contents of a specified artifact.
        If artifacts are stored with GZip compression, the default behavior
        is to return the artifact uncompressed (the mime_type response field
        indicates the exact format returned).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArtifact(self, request, context):
        """CreateArtifact creates a specified artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceArtifact(self, request, context):
        """ReplaceArtifact can be used to replace a specified artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArtifact(self, request, context):
        """DeleteArtifact removes a specified artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListApis': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApis,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApisRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApisResponse.SerializeToString,
            ),
            'GetApi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApi,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.SerializeToString,
            ),
            'CreateApi': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApi,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.SerializeToString,
            ),
            'UpdateApi': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApi,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.SerializeToString,
            ),
            'DeleteApi': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApi,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListApiVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiVersions,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiVersionsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiVersionsResponse.SerializeToString,
            ),
            'GetApiVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiVersion,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiVersionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.SerializeToString,
            ),
            'CreateApiVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiVersion,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiVersionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.SerializeToString,
            ),
            'UpdateApiVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApiVersion,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiVersionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.SerializeToString,
            ),
            'DeleteApiVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApiVersion,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiVersionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListApiSpecs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiSpecs,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecsResponse.SerializeToString,
            ),
            'GetApiSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiSpec,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiSpecRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.SerializeToString,
            ),
            'GetApiSpecContents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiSpecContents,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiSpecContentsRequest.FromString,
                    response_serializer=google_dot_api_dot_httpbody__pb2.HttpBody.SerializeToString,
            ),
            'CreateApiSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiSpec,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiSpecRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.SerializeToString,
            ),
            'UpdateApiSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApiSpec,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiSpecRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.SerializeToString,
            ),
            'DeleteApiSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApiSpec,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiSpecRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TagApiSpecRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.TagApiSpecRevision,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.TagApiSpecRevisionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.SerializeToString,
            ),
            'ListApiSpecRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiSpecRevisions,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecRevisionsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecRevisionsResponse.SerializeToString,
            ),
            'RollbackApiSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackApiSpec,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.RollbackApiSpecRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.SerializeToString,
            ),
            'DeleteApiSpecRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApiSpecRevision,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiSpecRevisionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.SerializeToString,
            ),
            'ListApiDeployments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiDeployments,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentsResponse.SerializeToString,
            ),
            'GetApiDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiDeployment,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiDeploymentRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.SerializeToString,
            ),
            'CreateApiDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiDeployment,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiDeploymentRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.SerializeToString,
            ),
            'UpdateApiDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApiDeployment,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiDeploymentRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.SerializeToString,
            ),
            'DeleteApiDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApiDeployment,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiDeploymentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TagApiDeploymentRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.TagApiDeploymentRevision,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.TagApiDeploymentRevisionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.SerializeToString,
            ),
            'ListApiDeploymentRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiDeploymentRevisions,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentRevisionsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentRevisionsResponse.SerializeToString,
            ),
            'RollbackApiDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackApiDeployment,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.RollbackApiDeploymentRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.SerializeToString,
            ),
            'DeleteApiDeploymentRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApiDeploymentRevision,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiDeploymentRevisionRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.SerializeToString,
            ),
            'ListArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArtifacts,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListArtifactsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListArtifactsResponse.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetArtifactRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.SerializeToString,
            ),
            'GetArtifactContents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifactContents,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetArtifactContentsRequest.FromString,
                    response_serializer=google_dot_api_dot_httpbody__pb2.HttpBody.SerializeToString,
            ),
            'CreateArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArtifact,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateArtifactRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.SerializeToString,
            ),
            'ReplaceArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceArtifact,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ReplaceArtifactRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.SerializeToString,
            ),
            'DeleteArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArtifact,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteArtifactRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.apigeeregistry.v1.Registry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Registry(object):
    """The Registry service allows teams to manage descriptions of APIs.
    """

    @staticmethod
    def ListApis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListApis',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApisRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetApi',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/CreateApi',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/UpdateApi',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Api.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteApi',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListApiVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListApiVersions',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiVersionsRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiVersionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetApiVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetApiVersion',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiVersionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApiVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/CreateApiVersion',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiVersionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApiVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/UpdateApiVersion',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiVersionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiVersion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApiVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteApiVersion',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiVersionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListApiSpecs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListApiSpecs',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecsRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetApiSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetApiSpec',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiSpecRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetApiSpecContents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetApiSpecContents',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiSpecContentsRequest.SerializeToString,
            google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApiSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/CreateApiSpec',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiSpecRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApiSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/UpdateApiSpec',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiSpecRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApiSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteApiSpec',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiSpecRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TagApiSpecRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/TagApiSpecRevision',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.TagApiSpecRevisionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListApiSpecRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListApiSpecRevisions',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecRevisionsRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiSpecRevisionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RollbackApiSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/RollbackApiSpec',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.RollbackApiSpecRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApiSpecRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteApiSpecRevision',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiSpecRevisionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListApiDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListApiDeployments',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentsRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetApiDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetApiDeployment',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetApiDeploymentRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApiDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/CreateApiDeployment',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateApiDeploymentRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApiDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/UpdateApiDeployment',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.UpdateApiDeploymentRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApiDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteApiDeployment',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiDeploymentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TagApiDeploymentRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/TagApiDeploymentRevision',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.TagApiDeploymentRevisionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListApiDeploymentRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListApiDeploymentRevisions',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentRevisionsRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListApiDeploymentRevisionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RollbackApiDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/RollbackApiDeployment',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.RollbackApiDeploymentRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApiDeploymentRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteApiDeploymentRevision',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteApiDeploymentRevisionRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.ApiDeployment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ListArtifacts',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListArtifactsRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ListArtifactsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetArtifact',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetArtifactRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArtifactContents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/GetArtifactContents',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.GetArtifactContentsRequest.SerializeToString,
            google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/CreateArtifact',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.CreateArtifactRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplaceArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/ReplaceArtifact',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.ReplaceArtifactRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__models__pb2.Artifact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Registry/DeleteArtifact',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_registry__service__pb2.DeleteArtifactRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
