# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/registry_notifications.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;google/cloud/apigeeregistry/v1/registry_notifications.proto\x12\x1egoogle.cloud.apigeeregistry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n\x0cNotification\x12\x43\n\x06\x63hange\x18\x01 \x01(\x0e\x32\x33.google.cloud.apigeeregistry.v1.Notification.Change\x12\x10\n\x08resource\x18\x02 \x01(\t\x12/\n\x0b\x63hange_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"G\n\x06\x43hange\x12\x16\n\x12\x43HANGE_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0b\n\x07UPDATED\x10\x02\x12\x0b\n\x07\x44\x45LETED\x10\x03\x42\x66\n\"com.google.cloud.apigeeregistry.v1B\x1aRegistryNotificationsProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_NOTIFICATION = DESCRIPTOR.message_types_by_name['Notification']
_NOTIFICATION_CHANGE = _NOTIFICATION.enum_types_by_name['Change']
Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'google.cloud.apigeeregistry.v1.registry_notifications_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.Notification)
  })
_sym_db.RegisterMessage(Notification)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.google.cloud.apigeeregistry.v1B\032RegistryNotificationsProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _NOTIFICATION._serialized_start=129
  _NOTIFICATION._serialized_end=352
  _NOTIFICATION_CHANGE._serialized_start=281
  _NOTIFICATION_CHANGE._serialized_end=352
# @@protoc_insertion_point(module_scope)
