# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.apigeeregistry.v1 import search_service_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2


class SearchStub(object):
    """Build and search an index of APIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Index = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Search/Index',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.IndexRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.Query = channel.unary_unary(
                '/google.cloud.apigeeregistry.v1.Search/Query',
                request_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.QueryResponse.FromString,
                )


class SearchServicer(object):
    """Build and search an index of APIs.
    """

    def Index(self, request, context):
        """Add a resource to the search index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Query the index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Index': grpc.unary_unary_rpc_method_handler(
                    servicer.Index,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.IndexRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.QueryRequest.FromString,
                    response_serializer=google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.apigeeregistry.v1.Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Search(object):
    """Build and search an index of APIs.
    """

    @staticmethod
    def Index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Search/Index',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.IndexRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.apigeeregistry.v1.Search/Query',
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.QueryRequest.SerializeToString,
            google_dot_cloud_dot_apigeeregistry_dot_v1_dot_search__service__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
