apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: registry-app-cert
spec:
  domains:
  # Replace the domain with your own custom domain or use the static IP address
  # with sslip.io domain (e.g. 1-2-3-4.sslip.io)
  - registry-app.example.com