apiVersion: apigeeregistry/v1
kind: ScoreDefinition
metadata:
  name: lint-error-percentage
data:
  display_name: "Lint Error Percentage"
  description: "Percentage of lint errors found"
  uri: "https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules"
  uri_display_name: "Spectral rules"
  target_resource:
    pattern: "apis/-/versions/-/specs/-"
  rollup_formula:
    score_formulas:
    - artifact:
        pattern: "$resource.spec/artifacts/conformance-apihub-styleguide"
      score_expression: "has(guidelineReportGroups[2].guidelineReports) ? sum(guidelineReportGroups[2].guidelineReports.map(r, has(r.ruleReportGroups[1].ruleReports) ? size(r.ruleReportGroups[1].ruleReports) : 0)) : 0"
      reference_id: "num_errors"
    - artifact:
        pattern: "$resource.spec/artifacts/complexity"
      score_expression: "getCount + postCount + deleteCount"
      reference_id: "num_operations"
    rollup_expression: "num_operations > 0.0 ? double(num_errors)/double(num_operations)*100.0 : 0"
  percent:
    thresholds: 
    - severity: ALERT
      range:
        min: 20
        max: 100
    - severity: WARNING
      range:
        min: 10
        max: 19
    - severity: OK
      range:
        min: 0
        max: 9