apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-spec-renderer
  labels:
    app: registry-spec-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-spec-renderer
  template:
    metadata:
      name: registry-spec-renderer
      labels:
        app: registry-spec-renderer
    spec:
      containers:
      - name: webapp
        image: ghcr.io/apigee/registry-spec-renderer:main
        env:
        - name: "PORT"
          value: "8080"
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/var/run/secret/cloud.google.com/service-account.json"
        volumeMounts:
        - name: "service-account"
          mountPath: "/var/run/secret/cloud.google.com"
      volumes:
      - name: "service-account"
        secret:
          secretName: "registry-spec-renderer-sa-key"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-spec-renderer-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: registry-spec-renderer