apiVersion: apigeeregistry/v1
kind: ScoreDefinition
metadata:
  name: apihub-lint-148
data:
  displayName: Lint Errors
  description: Number of lint errors found for AIP-148 in conformance report
  uri: https://linter.aip.dev/148
  uriDisplayName: AIP-148 rules
  targetResource:
    pattern: apis/-/versions/-/specs/-
    filter: ""
  scoreFormula:
    artifact:
      pattern: $resource.spec/artifacts/conformance-apihub-styleguide
      filter: ""
    scoreExpression: 'has(guidelineReportGroups[2].guidelineReports) ? sum(guidelineReportGroups[2].guidelineReports.filter(g, g.guidelineId == "aip148").map(r, has(r.ruleReportGroups[1].ruleReports) ? size(r.ruleReportGroups[1].ruleReports) : 0)) : 0'
    referenceId: ""
  integer:
    minValue: 0
    thresholds: []
