# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/controller/manifest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8google/cloud/apigeeregistry/v1/controller/manifest.proto\x12)google.cloud.apigeeregistry.v1.controller\x1a\x1fgoogle/api/field_behavior.proto\"\xaf\x01\n\x08Manifest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12^\n\x13generated_resources\x18\x05 \x03(\x0b\x32<.google.cloud.apigeeregistry.v1.controller.GeneratedResourceB\x03\xe0\x41\x02\"\xac\x01\n\x11GeneratedResource\x12\x14\n\x07pattern\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\t\x12\x0f\n\x07receipt\x18\x03 \x01(\x08\x12K\n\x0c\x64\x65pendencies\x18\x04 \x03(\x0b\x32\x35.google.cloud.apigeeregistry.v1.controller.Dependency\x12\x13\n\x06\x61\x63tion\x18\x05 \x01(\tB\x03\xe0\x41\x02\"2\n\nDependency\x12\x14\n\x07pattern\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\tBn\n-com.google.cloud.apigeeregistry.v1.controllerB\x17\x43ontrollerManifestProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_MANIFEST = DESCRIPTOR.message_types_by_name['Manifest']
_GENERATEDRESOURCE = DESCRIPTOR.message_types_by_name['GeneratedResource']
_DEPENDENCY = DESCRIPTOR.message_types_by_name['Dependency']
Manifest = _reflection.GeneratedProtocolMessageType('Manifest', (_message.Message,), {
  'DESCRIPTOR' : _MANIFEST,
  '__module__' : 'google.cloud.apigeeregistry.v1.controller.manifest_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.controller.Manifest)
  })
_sym_db.RegisterMessage(Manifest)

GeneratedResource = _reflection.GeneratedProtocolMessageType('GeneratedResource', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEDRESOURCE,
  '__module__' : 'google.cloud.apigeeregistry.v1.controller.manifest_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.controller.GeneratedResource)
  })
_sym_db.RegisterMessage(GeneratedResource)

Dependency = _reflection.GeneratedProtocolMessageType('Dependency', (_message.Message,), {
  'DESCRIPTOR' : _DEPENDENCY,
  '__module__' : 'google.cloud.apigeeregistry.v1.controller.manifest_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.controller.Dependency)
  })
_sym_db.RegisterMessage(Dependency)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.google.cloud.apigeeregistry.v1.controllerB\027ControllerManifestProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _MANIFEST.fields_by_name['generated_resources']._options = None
  _MANIFEST.fields_by_name['generated_resources']._serialized_options = b'\340A\002'
  _GENERATEDRESOURCE.fields_by_name['pattern']._options = None
  _GENERATEDRESOURCE.fields_by_name['pattern']._serialized_options = b'\340A\002'
  _GENERATEDRESOURCE.fields_by_name['action']._options = None
  _GENERATEDRESOURCE.fields_by_name['action']._serialized_options = b'\340A\002'
  _DEPENDENCY.fields_by_name['pattern']._options = None
  _DEPENDENCY.fields_by_name['pattern']._serialized_options = b'\340A\002'
  _MANIFEST._serialized_start=137
  _MANIFEST._serialized_end=312
  _GENERATEDRESOURCE._serialized_start=315
  _GENERATEDRESOURCE._serialized_end=487
  _DEPENDENCY._serialized_start=489
  _DEPENDENCY._serialized_end=539
# @@protoc_insertion_point(module_scope)
