apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: factchecktools
data:
  displayName: factchecktools
  description: Fact Check Tools API
  versions:
    - metadata:
        name: v1alpha1
      data:
        specs:
          - metadata:
              name: openapi.yaml
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3
              sourceURI: file:///specs/factchecktools/v1alpha1/openapi.yaml
