apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: googleapis.com-books
data:
  displayName: googleapis.com-books
  description: Books API
  versions:
    - metadata:
        name: v1
      data:
        specs:
          - metadata:
              name: openapi.yaml
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3
              sourceURI: https://github.com/APIs-guru/openapi-directory/blob/4262544a5067f9df2efa5622cc21890afd6e06be/APIs/googleapis.com/books/v1/openapi.yaml
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-dependencies
      data:
        displayName: ""
        description: Defines a list of dependencies
        references: []
    - kind: ReferenceList
      metadata:
        name: apihub-related
      data:
        displayName: ""
        description: Defines a list of related resources
        references: []
