apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: policytroubleshooter
data:
  displayName: policytroubleshooter
  description: Policy Troubleshooter API
  versions:
    - metadata:
        name: v1
      data:
        specs:
          - metadata:
              name: openapi.yaml
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3
              sourceURI: file:///specs/policytroubleshooter/v1/openapi.yaml
    - metadata:
        name: v1beta
      data:
        specs:
          - metadata:
              name: openapi.yaml
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3
              sourceURI: file:///specs/policytroubleshooter/v1beta/openapi.yaml
