# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/scoring/score.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.cloud.apigeeregistry.v1.scoring import severity_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_scoring_dot_severity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2google/cloud/apigeeregistry/v1/scoring/score.proto\x12&google.cloud.apigeeregistry.v1.scoring\x1a\x1fgoogle/api/field_behavior.proto\x1a\x35google/cloud/apigeeregistry/v1/scoring/severity.proto\"\xd0\x03\n\x05Score\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0b\n\x03uri\x18\x05 \x01(\t\x12\x18\n\x10uri_display_name\x18\x06 \x01(\t\x12\x1c\n\x0f\x64\x65\x66inition_name\x18\x07 \x01(\tB\x03\xe0\x41\x02\x12\x42\n\x08severity\x18\x08 \x01(\x0e\x32\x30.google.cloud.apigeeregistry.v1.scoring.Severity\x12M\n\rpercent_value\x18\t \x01(\x0b\x32\x34.google.cloud.apigeeregistry.v1.scoring.PercentValueH\x00\x12M\n\rinteger_value\x18\n \x01(\x0b\x32\x34.google.cloud.apigeeregistry.v1.scoring.IntegerValueH\x00\x12M\n\rboolean_value\x18\x0b \x01(\x0b\x32\x34.google.cloud.apigeeregistry.v1.scoring.BooleanValueH\x00\x42\x07\n\x05value\"\"\n\x0cPercentValue\x12\x12\n\x05value\x18\x01 \x01(\x02\x42\x03\xe0\x41\x02\"H\n\x0cIntegerValue\x12\x12\n\x05value\x18\x01 \x01(\x05\x42\x03\xe0\x41\x02\x12\x11\n\tmin_value\x18\x02 \x01(\x05\x12\x11\n\tmax_value\x18\x03 \x01(\x05\"9\n\x0c\x42ooleanValue\x12\x12\n\x05value\x18\x01 \x01(\x08\x42\x03\xe0\x41\x02\x12\x15\n\rdisplay_value\x18\x02 \x01(\tBe\n*com.google.cloud.apigeeregistry.v1.scoringB\x11ScoringScoreProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_SCORE = DESCRIPTOR.message_types_by_name['Score']
_PERCENTVALUE = DESCRIPTOR.message_types_by_name['PercentValue']
_INTEGERVALUE = DESCRIPTOR.message_types_by_name['IntegerValue']
_BOOLEANVALUE = DESCRIPTOR.message_types_by_name['BooleanValue']
Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
  'DESCRIPTOR' : _SCORE,
  '__module__' : 'google.cloud.apigeeregistry.v1.scoring.score_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.scoring.Score)
  })
_sym_db.RegisterMessage(Score)

PercentValue = _reflection.GeneratedProtocolMessageType('PercentValue', (_message.Message,), {
  'DESCRIPTOR' : _PERCENTVALUE,
  '__module__' : 'google.cloud.apigeeregistry.v1.scoring.score_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.scoring.PercentValue)
  })
_sym_db.RegisterMessage(PercentValue)

IntegerValue = _reflection.GeneratedProtocolMessageType('IntegerValue', (_message.Message,), {
  'DESCRIPTOR' : _INTEGERVALUE,
  '__module__' : 'google.cloud.apigeeregistry.v1.scoring.score_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.scoring.IntegerValue)
  })
_sym_db.RegisterMessage(IntegerValue)

BooleanValue = _reflection.GeneratedProtocolMessageType('BooleanValue', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEANVALUE,
  '__module__' : 'google.cloud.apigeeregistry.v1.scoring.score_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.scoring.BooleanValue)
  })
_sym_db.RegisterMessage(BooleanValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.google.cloud.apigeeregistry.v1.scoringB\021ScoringScoreProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _SCORE.fields_by_name['id']._options = None
  _SCORE.fields_by_name['id']._serialized_options = b'\340A\002'
  _SCORE.fields_by_name['definition_name']._options = None
  _SCORE.fields_by_name['definition_name']._serialized_options = b'\340A\002'
  _PERCENTVALUE.fields_by_name['value']._options = None
  _PERCENTVALUE.fields_by_name['value']._serialized_options = b'\340A\002'
  _INTEGERVALUE.fields_by_name['value']._options = None
  _INTEGERVALUE.fields_by_name['value']._serialized_options = b'\340A\002'
  _BOOLEANVALUE.fields_by_name['value']._options = None
  _BOOLEANVALUE.fields_by_name['value']._serialized_options = b'\340A\002'
  _SCORE._serialized_start=183
  _SCORE._serialized_end=647
  _PERCENTVALUE._serialized_start=649
  _PERCENTVALUE._serialized_end=683
  _INTEGERVALUE._serialized_start=685
  _INTEGERVALUE._serialized_end=757
  _BOOLEANVALUE._serialized_start=759
  _BOOLEANVALUE._serialized_end=816
# @@protoc_insertion_point(module_scope)
