# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/v1/scoring/score_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.cloud.apigeeregistry.v1.scoring import score_pb2 as google_dot_cloud_dot_apigeeregistry_dot_v1_dot_scoring_dot_score__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7google/cloud/apigeeregistry/v1/scoring/score_card.proto\x12&google.cloud.apigeeregistry.v1.scoring\x1a\x1fgoogle/api/field_behavior.proto\x1a\x32google/cloud/apigeeregistry/v1/scoring/score.proto\"\xb7\x01\n\tScoreCard\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1c\n\x0f\x64\x65\x66inition_name\x18\x05 \x01(\tB\x03\xe0\x41\x02\x12\x42\n\x06scores\x18\x06 \x03(\x0b\x32-.google.cloud.apigeeregistry.v1.scoring.ScoreB\x03\xe0\x41\x02\x42i\n*com.google.cloud.apigeeregistry.v1.scoringB\x15ScoringScoreCardProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_SCORECARD = DESCRIPTOR.message_types_by_name['ScoreCard']
ScoreCard = _reflection.GeneratedProtocolMessageType('ScoreCard', (_message.Message,), {
  'DESCRIPTOR' : _SCORECARD,
  '__module__' : 'google.cloud.apigeeregistry.v1.scoring.score_card_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.v1.scoring.ScoreCard)
  })
_sym_db.RegisterMessage(ScoreCard)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.google.cloud.apigeeregistry.v1.scoringB\025ScoringScoreCardProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _SCORECARD.fields_by_name['id']._options = None
  _SCORECARD.fields_by_name['id']._serialized_options = b'\340A\002'
  _SCORECARD.fields_by_name['definition_name']._options = None
  _SCORECARD.fields_by_name['definition_name']._serialized_options = b'\340A\002'
  _SCORECARD.fields_by_name['scores']._options = None
  _SCORECARD.fields_by_name['scores']._serialized_options = b'\340A\002'
  _SCORECARD._serialized_start=185
  _SCORECARD._serialized_end=368
# @@protoc_insertion_point(module_scope)
