# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/applications/v1alpha1/diff_analytics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFgoogle/cloud/apigeeregistry/applications/v1alpha1/diff_analytics.proto\x12\x31google.cloud.apigeeregistry.applications.v1alpha1\"\xb3\x02\n\x04\x44iff\x12\x11\n\tadditions\x18\x01 \x03(\t\x12\x11\n\tdeletions\x18\x02 \x03(\t\x12\x61\n\rmodifications\x18\x03 \x03(\x0b\x32J.google.cloud.apigeeregistry.applications.v1alpha1.Diff.ModificationsEntry\x1a\'\n\x0bValueChange\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x1ay\n\x12ModificationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12R\n\x05value\x18\x02 \x01(\x0b\x32\x43.google.cloud.apigeeregistry.applications.v1alpha1.Diff.ValueChange:\x02\x38\x01\"\x8b\x02\n\rChangeDetails\x12Q\n\x10\x62reaking_changes\x18\x01 \x01(\x0b\x32\x37.google.cloud.apigeeregistry.applications.v1alpha1.Diff\x12U\n\x14non_breaking_changes\x18\x02 \x01(\x0b\x32\x37.google.cloud.apigeeregistry.applications.v1alpha1.Diff\x12P\n\x0funknown_changes\x18\x03 \x01(\x0b\x32\x37.google.cloud.apigeeregistry.applications.v1alpha1.Diff\"b\n\x0b\x43hangeStats\x12\x1d\n\x15\x62reaking_change_count\x18\x01 \x01(\x03\x12 \n\x18nonbreaking_change_count\x18\x02 \x01(\x03\x12\x12\n\ndiff_count\x18\x03 \x01(\x03\"Q\n\rChangeMetrics\x12\"\n\x1a\x62reaking_change_percentage\x18\x01 \x01(\x01\x12\x1c\n\x14\x62reaking_change_rate\x18\x02 \x01(\x01\x42$Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_DIFF = DESCRIPTOR.message_types_by_name['Diff']
_DIFF_VALUECHANGE = _DIFF.nested_types_by_name['ValueChange']
_DIFF_MODIFICATIONSENTRY = _DIFF.nested_types_by_name['ModificationsEntry']
_CHANGEDETAILS = DESCRIPTOR.message_types_by_name['ChangeDetails']
_CHANGESTATS = DESCRIPTOR.message_types_by_name['ChangeStats']
_CHANGEMETRICS = DESCRIPTOR.message_types_by_name['ChangeMetrics']
Diff = _reflection.GeneratedProtocolMessageType('Diff', (_message.Message,), {

  'ValueChange' : _reflection.GeneratedProtocolMessageType('ValueChange', (_message.Message,), {
    'DESCRIPTOR' : _DIFF_VALUECHANGE,
    '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.diff_analytics_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.Diff.ValueChange)
    })
  ,

  'ModificationsEntry' : _reflection.GeneratedProtocolMessageType('ModificationsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DIFF_MODIFICATIONSENTRY,
    '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.diff_analytics_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.Diff.ModificationsEntry)
    })
  ,
  'DESCRIPTOR' : _DIFF,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.diff_analytics_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.Diff)
  })
_sym_db.RegisterMessage(Diff)
_sym_db.RegisterMessage(Diff.ValueChange)
_sym_db.RegisterMessage(Diff.ModificationsEntry)

ChangeDetails = _reflection.GeneratedProtocolMessageType('ChangeDetails', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEDETAILS,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.diff_analytics_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.ChangeDetails)
  })
_sym_db.RegisterMessage(ChangeDetails)

ChangeStats = _reflection.GeneratedProtocolMessageType('ChangeStats', (_message.Message,), {
  'DESCRIPTOR' : _CHANGESTATS,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.diff_analytics_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.ChangeStats)
  })
_sym_db.RegisterMessage(ChangeStats)

ChangeMetrics = _reflection.GeneratedProtocolMessageType('ChangeMetrics', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEMETRICS,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.diff_analytics_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.ChangeMetrics)
  })
_sym_db.RegisterMessage(ChangeMetrics)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/apigee/registry/rpc;rpc'
  _DIFF_MODIFICATIONSENTRY._options = None
  _DIFF_MODIFICATIONSENTRY._serialized_options = b'8\001'
  _DIFF._serialized_start=126
  _DIFF._serialized_end=433
  _DIFF_VALUECHANGE._serialized_start=271
  _DIFF_VALUECHANGE._serialized_end=310
  _DIFF_MODIFICATIONSENTRY._serialized_start=312
  _DIFF_MODIFICATIONSENTRY._serialized_end=433
  _CHANGEDETAILS._serialized_start=436
  _CHANGEDETAILS._serialized_end=703
  _CHANGESTATS._serialized_start=705
  _CHANGESTATS._serialized_end=803
  _CHANGEMETRICS._serialized_start=805
  _CHANGEMETRICS._serialized_end=886
# @@protoc_insertion_point(module_scope)
