# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/applications/v1alpha1/registry_references.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKgoogle/cloud/apigeeregistry/applications/v1alpha1/registry_references.proto\x12\x31google.cloud.apigeeregistry.applications.v1alpha1\"G\n\nReferences\x12\x1b\n\x13\x65xternal_references\x18\x01 \x03(\t\x12\x1c\n\x14\x61vailable_references\x18\x02 \x03(\tBv\n5com.google.cloud.apigeeregistry.applications.v1alpha1B\x17RegistryReferencesProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_REFERENCES = DESCRIPTOR.message_types_by_name['References']
References = _reflection.GeneratedProtocolMessageType('References', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCES,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.registry_references_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.References)
  })
_sym_db.RegisterMessage(References)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n5com.google.cloud.apigeeregistry.applications.v1alpha1B\027RegistryReferencesProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _REFERENCES._serialized_start=130
  _REFERENCES._serialized_end=201
# @@protoc_insertion_point(module_scope)
