# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/applications/v1alpha1/registry_conformance_report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.cloud.apigeeregistry.applications.v1alpha1 import registry_styleguide_pb2 as google_dot_cloud_dot_apigeeregistry_dot_applications_dot_v1alpha1_dot_registry__styleguide__pb2
from google.cloud.apigeeregistry.applications.v1alpha1 import registry_lint_pb2 as google_dot_cloud_dot_apigeeregistry_dot_applications_dot_v1alpha1_dot_registry__lint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSgoogle/cloud/apigeeregistry/applications/v1alpha1/registry_conformance_report.proto\x12\x31google.cloud.apigeeregistry.applications.v1alpha1\x1a\x1fgoogle/api/field_behavior.proto\x1aKgoogle/cloud/apigeeregistry/applications/v1alpha1/registry_styleguide.proto\x1a\x45google/cloud/apigeeregistry/applications/v1alpha1/registry_lint.proto\"\xae\x01\n\x11\x43onformanceReport\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x1c\n\x0fstyleguide_name\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12h\n\x17guideline_report_groups\x18\x03 \x03(\x0b\x32G.google.cloud.apigeeregistry.applications.v1alpha1.GuidelineReportGroup\"\x8c\x01\n\x0fGuidelineReport\x12\x19\n\x0cguideline_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12^\n\x12rule_report_groups\x18\x02 \x03(\x0b\x32\x42.google.cloud.apigeeregistry.applications.v1alpha1.RuleReportGroup\"\xb9\x01\n\nRuleReport\x12\x14\n\x07rule_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x16\n\tspec_name\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12\x16\n\tfile_name\x18\x03 \x01(\tB\x03\xe0\x41\x02\x12\x12\n\nsuggestion\x18\x04 \x01(\t\x12Q\n\x08location\x18\x05 \x01(\x0b\x32?.google.cloud.apigeeregistry.applications.v1alpha1.LintLocation\"\xd4\x01\n\x14GuidelineReportGroup\x12X\n\x06status\x18\x01 \x01(\x0e\x32\x43.google.cloud.apigeeregistry.applications.v1alpha1.Guideline.StatusB\x03\xe0\x41\x02\x12\x62\n\x11guideline_reports\x18\x02 \x03(\x0b\x32\x42.google.cloud.apigeeregistry.applications.v1alpha1.GuidelineReportB\x03\xe0\x41\x02\"\xc4\x01\n\x0fRuleReportGroup\x12W\n\x08severity\x18\x01 \x01(\x0e\x32@.google.cloud.apigeeregistry.applications.v1alpha1.Rule.SeverityB\x03\xe0\x41\x02\x12X\n\x0crule_reports\x18\x02 \x03(\x0b\x32=.google.cloud.apigeeregistry.applications.v1alpha1.RuleReportB\x03\xe0\x41\x02\x42}\n5com.google.cloud.apigeeregistry.applications.v1alpha1B\x1eRegistryConformanceReportProtoP\x01Z\"github.com/apigee/registry/rpc;rpcb\x06proto3')



_CONFORMANCEREPORT = DESCRIPTOR.message_types_by_name['ConformanceReport']
_GUIDELINEREPORT = DESCRIPTOR.message_types_by_name['GuidelineReport']
_RULEREPORT = DESCRIPTOR.message_types_by_name['RuleReport']
_GUIDELINEREPORTGROUP = DESCRIPTOR.message_types_by_name['GuidelineReportGroup']
_RULEREPORTGROUP = DESCRIPTOR.message_types_by_name['RuleReportGroup']
ConformanceReport = _reflection.GeneratedProtocolMessageType('ConformanceReport', (_message.Message,), {
  'DESCRIPTOR' : _CONFORMANCEREPORT,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.registry_conformance_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.ConformanceReport)
  })
_sym_db.RegisterMessage(ConformanceReport)

GuidelineReport = _reflection.GeneratedProtocolMessageType('GuidelineReport', (_message.Message,), {
  'DESCRIPTOR' : _GUIDELINEREPORT,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.registry_conformance_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.GuidelineReport)
  })
_sym_db.RegisterMessage(GuidelineReport)

RuleReport = _reflection.GeneratedProtocolMessageType('RuleReport', (_message.Message,), {
  'DESCRIPTOR' : _RULEREPORT,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.registry_conformance_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.RuleReport)
  })
_sym_db.RegisterMessage(RuleReport)

GuidelineReportGroup = _reflection.GeneratedProtocolMessageType('GuidelineReportGroup', (_message.Message,), {
  'DESCRIPTOR' : _GUIDELINEREPORTGROUP,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.registry_conformance_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.GuidelineReportGroup)
  })
_sym_db.RegisterMessage(GuidelineReportGroup)

RuleReportGroup = _reflection.GeneratedProtocolMessageType('RuleReportGroup', (_message.Message,), {
  'DESCRIPTOR' : _RULEREPORTGROUP,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.registry_conformance_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.RuleReportGroup)
  })
_sym_db.RegisterMessage(RuleReportGroup)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n5com.google.cloud.apigeeregistry.applications.v1alpha1B\036RegistryConformanceReportProtoP\001Z\"github.com/apigee/registry/rpc;rpc'
  _CONFORMANCEREPORT.fields_by_name['name']._options = None
  _CONFORMANCEREPORT.fields_by_name['name']._serialized_options = b'\340A\002'
  _CONFORMANCEREPORT.fields_by_name['styleguide_name']._options = None
  _CONFORMANCEREPORT.fields_by_name['styleguide_name']._serialized_options = b'\340A\002'
  _GUIDELINEREPORT.fields_by_name['guideline_id']._options = None
  _GUIDELINEREPORT.fields_by_name['guideline_id']._serialized_options = b'\340A\002'
  _RULEREPORT.fields_by_name['rule_id']._options = None
  _RULEREPORT.fields_by_name['rule_id']._serialized_options = b'\340A\002'
  _RULEREPORT.fields_by_name['spec_name']._options = None
  _RULEREPORT.fields_by_name['spec_name']._serialized_options = b'\340A\002'
  _RULEREPORT.fields_by_name['file_name']._options = None
  _RULEREPORT.fields_by_name['file_name']._serialized_options = b'\340A\002'
  _GUIDELINEREPORTGROUP.fields_by_name['status']._options = None
  _GUIDELINEREPORTGROUP.fields_by_name['status']._serialized_options = b'\340A\002'
  _GUIDELINEREPORTGROUP.fields_by_name['guideline_reports']._options = None
  _GUIDELINEREPORTGROUP.fields_by_name['guideline_reports']._serialized_options = b'\340A\002'
  _RULEREPORTGROUP.fields_by_name['severity']._options = None
  _RULEREPORTGROUP.fields_by_name['severity']._serialized_options = b'\340A\002'
  _RULEREPORTGROUP.fields_by_name['rule_reports']._options = None
  _RULEREPORTGROUP.fields_by_name['rule_reports']._serialized_options = b'\340A\002'
  _CONFORMANCEREPORT._serialized_start=320
  _CONFORMANCEREPORT._serialized_end=494
  _GUIDELINEREPORT._serialized_start=497
  _GUIDELINEREPORT._serialized_end=637
  _RULEREPORT._serialized_start=640
  _RULEREPORT._serialized_end=825
  _GUIDELINEREPORTGROUP._serialized_start=828
  _GUIDELINEREPORTGROUP._serialized_end=1040
  _RULEREPORTGROUP._serialized_start=1043
  _RULEREPORTGROUP._serialized_end=1239
# @@protoc_insertion_point(module_scope)
