# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/applications/v1alpha1/consistency/consistency_report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.cloud.apigeeregistry.applications.v1alpha1.consistency import word_group_pb2 as google_dot_cloud_dot_apigeeregistry_dot_applications_dot_v1alpha1_dot_consistency_dot_word__group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVgoogle/cloud/apigeeregistry/applications/v1alpha1/consistency/consistency_report.proto\x12=google.cloud.apigeeregistry.applications.v1alpha1.consistency\x1a\x1fgoogle/api/field_behavior.proto\x1aNgoogle/cloud/apigeeregistry/applications/v1alpha1/consistency/word_group.proto\"\xba\x03\n\x11\x43onsistencyReport\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x11\n\x04kind\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12v\n\x12\x63urrent_variations\x18\x03 \x03(\x0b\x32Z.google.cloud.apigeeregistry.applications.v1alpha1.consistency.ConsistencyReport.Variation\x12s\n\x0fpast_variations\x18\x04 \x03(\x0b\x32Z.google.cloud.apigeeregistry.applications.v1alpha1.consistency.ConsistencyReport.Variation\x12\x14\n\x0cunique_terms\x18\x05 \x03(\t\x1a~\n\tVariation\x12\x11\n\x04term\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12^\n\x07\x63luster\x18\x02 \x01(\x0b\x32H.google.cloud.apigeeregistry.applications.v1alpha1.consistency.WordGroupB\x03\xe0\x41\x02\x62\x06proto3')



_CONSISTENCYREPORT = DESCRIPTOR.message_types_by_name['ConsistencyReport']
_CONSISTENCYREPORT_VARIATION = _CONSISTENCYREPORT.nested_types_by_name['Variation']
ConsistencyReport = _reflection.GeneratedProtocolMessageType('ConsistencyReport', (_message.Message,), {

  'Variation' : _reflection.GeneratedProtocolMessageType('Variation', (_message.Message,), {
    'DESCRIPTOR' : _CONSISTENCYREPORT_VARIATION,
    '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.consistency.consistency_report_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.consistency.ConsistencyReport.Variation)
    })
  ,
  'DESCRIPTOR' : _CONSISTENCYREPORT,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.consistency.consistency_report_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.consistency.ConsistencyReport)
  })
_sym_db.RegisterMessage(ConsistencyReport)
_sym_db.RegisterMessage(ConsistencyReport.Variation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSISTENCYREPORT_VARIATION.fields_by_name['term']._options = None
  _CONSISTENCYREPORT_VARIATION.fields_by_name['term']._serialized_options = b'\340A\002'
  _CONSISTENCYREPORT_VARIATION.fields_by_name['cluster']._options = None
  _CONSISTENCYREPORT_VARIATION.fields_by_name['cluster']._serialized_options = b'\340A\002'
  _CONSISTENCYREPORT.fields_by_name['id']._options = None
  _CONSISTENCYREPORT.fields_by_name['id']._serialized_options = b'\340A\002'
  _CONSISTENCYREPORT.fields_by_name['kind']._options = None
  _CONSISTENCYREPORT.fields_by_name['kind']._serialized_options = b'\340A\002'
  _CONSISTENCYREPORT._serialized_start=267
  _CONSISTENCYREPORT._serialized_end=709
  _CONSISTENCYREPORT_VARIATION._serialized_start=583
  _CONSISTENCYREPORT_VARIATION._serialized_end=709
# @@protoc_insertion_point(module_scope)
