# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/apigeeregistry/applications/v1alpha1/consistency/word_group.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNgoogle/cloud/apigeeregistry/applications/v1alpha1/consistency/word_group.proto\x12=google.cloud.apigeeregistry.applications.v1alpha1.consistency\x1a\x1fgoogle/api/field_behavior.proto\"\xdf\x01\n\tWordGroup\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x11\n\x04kind\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12x\n\x0eword_frequency\x18\x03 \x03(\x0b\x32[.google.cloud.apigeeregistry.applications.v1alpha1.consistency.WordGroup.WordFrequencyEntryB\x03\xe0\x41\x02\x1a\x34\n\x12WordFrequencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')



_WORDGROUP = DESCRIPTOR.message_types_by_name['WordGroup']
_WORDGROUP_WORDFREQUENCYENTRY = _WORDGROUP.nested_types_by_name['WordFrequencyEntry']
WordGroup = _reflection.GeneratedProtocolMessageType('WordGroup', (_message.Message,), {

  'WordFrequencyEntry' : _reflection.GeneratedProtocolMessageType('WordFrequencyEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORDGROUP_WORDFREQUENCYENTRY,
    '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.consistency.word_group_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.consistency.WordGroup.WordFrequencyEntry)
    })
  ,
  'DESCRIPTOR' : _WORDGROUP,
  '__module__' : 'google.cloud.apigeeregistry.applications.v1alpha1.consistency.word_group_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.apigeeregistry.applications.v1alpha1.consistency.WordGroup)
  })
_sym_db.RegisterMessage(WordGroup)
_sym_db.RegisterMessage(WordGroup.WordFrequencyEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORDGROUP_WORDFREQUENCYENTRY._options = None
  _WORDGROUP_WORDFREQUENCYENTRY._serialized_options = b'8\001'
  _WORDGROUP.fields_by_name['id']._options = None
  _WORDGROUP.fields_by_name['id']._serialized_options = b'\340A\002'
  _WORDGROUP.fields_by_name['kind']._options = None
  _WORDGROUP.fields_by_name['kind']._serialized_options = b'\340A\002'
  _WORDGROUP.fields_by_name['word_frequency']._options = None
  _WORDGROUP.fields_by_name['word_frequency']._serialized_options = b'\340A\002'
  _WORDGROUP._serialized_start=179
  _WORDGROUP._serialized_end=402
  _WORDGROUP_WORDFREQUENCYENTRY._serialized_start=350
  _WORDGROUP_WORDFREQUENCYENTRY._serialized_end=402
# @@protoc_insertion_point(module_scope)
