// Copyright 2020 Google LLC. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/compute"
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/count"
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/export"
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/extract"
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/generate"
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/search"
	"github.com/apigee/registry-experimental/cmd/registry-experimental/cmd/wipeout"
	pkgconf "github.com/apigee/registry/pkg/config"
	"github.com/spf13/cobra"
)

// Version value will be replaced by the release tag when the binaries are
// generated by GoReleaser.
var Version = "dev"

func Command() *cobra.Command {
	var cmd = &cobra.Command{
		Use:     "registry-experimental",
		Version: Version,
		Short:   "Experimental utilities for working with the API Registry",
	}
	cmd.PersistentFlags().AddFlagSet(pkgconf.Flags)

	cmd.AddCommand(compute.Command())
	cmd.AddCommand(count.Command())
	cmd.AddCommand(export.Command())
	cmd.AddCommand(extract.Command())
	cmd.AddCommand(generate.Command())
	cmd.AddCommand(search.Command())
	cmd.AddCommand(wipeout.Command())
	return cmd
}
