apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: bookstore
data:
  displayName: Bookstore Example API
  description: A simple Google Example Library API.
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-dependencies
      data:
        displayName: ""
        description: Defines a list of dependencies
        references: []
    - kind: ReferenceList
      metadata:
        name: apihub-related
      data:
        displayName: ""
        description: Defines a list of related resources
        references: []

